In [1]:
import pandas as pd


tweets="data/file_name.csv"
tweets_df = pd.read_csv(tweets)
tweets_df.head()

time            id           handle  \
0   9/28/2016 0:22  7.809260e+17   HillaryClinton   
1  9/27/2016 23:08  7.809070e+17   HillaryClinton   
2  9/27/2016 22:30  7.808970e+17   HillaryClinton   
3  9/27/2016 22:13  7.808930e+17  realDonaldTrump   
4  9/27/2016 21:35  7.808840e+17   HillaryClinton   

                                                text  is_retweet  \
0  The question in this election Who can put the ...       False   
1  If we stand together theres nothing we cant do...       False   
2  Both candidates were asked about how theyd con...       False   
3  Join me for a 3pm rally tomorrow at the MidAme...       False   
4  This election is too important to sit out Go t...       False   

   original_author in_reply_to_screen_name  in_reply_to_status_id  \
0              NaN                     NaN                    NaN   
1              NaN                     NaN                    NaN   
2              NaN                     NaN                    NaN   
3              NaN                     NaN                    NaN   
4              NaN                     NaN                    NaN   

   in_reply_to_user_id  is_quote_status  ... place_type  place_country_code  \
0                  NaN            False  ...        NaN                 NaN   
1                  NaN            False  ...        NaN                 NaN   
2                  NaN            False  ...        NaN                 NaN   
3                  NaN            False  ...        NaN                 NaN   
4                  NaN            False  ...        NaN                 NaN   

   place_country  place_contained_within  place_attributes place_bounding_box  \
0            NaN                     NaN               NaN                NaN   
1            NaN                     NaN               NaN                NaN   
2            NaN                     NaN               NaN                NaN   
3            NaN                     NaN               NaN                NaN   
4            NaN                     NaN               NaN                NaN   

                                     source_url truncated  \
0                    https://studio.twitter.com     False   
1                    https://studio.twitter.com     False   
2  https://about.twitter.com/products/tweetdeck     False   
3            http://twitter.com/download/iphone      True   
4  https://about.twitter.com/products/tweetdeck     False   

                                            entities  \
0  {'media': [{'display_url': 'pic.twitter.com/Xr...   
1  {'media': [{'display_url': 'pic.twitter.com/Q3...   
2  {'user_mentions': [], 'symbols': [], 'urls': [...   
3  {'user_mentions': [], 'symbols': [], 'urls': [...   
4  {'user_mentions': [], 'symbols': [], 'urls': [...   

                                   extended_entities  
0  {'media': [{'display_url': 'pic.twitter.com/Xr...  
1  {'media': [{'display_url': 'pic.twitter.com/Q3...  
2                                                NaN  
3                                                NaN  
4                                                NaN  

[5 rows x 28 columns]

In [2]:
#only take handle and text columns
new_df=tweets_df[['handle','text']]

new_df.head()

handle                                               text
0   HillaryClinton  The question in this election Who can put the ...
1   HillaryClinton  If we stand together theres nothing we cant do...
2   HillaryClinton  Both candidates were asked about how theyd con...
3  realDonaldTrump  Join me for a 3pm rally tomorrow at the MidAme...
4   HillaryClinton  This election is too important to sit out Go t...

In [3]:
#convert handle into label 0 or 1
mapping = {'realDonaldTrump': 0, 'HillaryClinton': 1}

new_df2=new_df.replace({'handle': mapping})

new_df2.head()

handle                                               text
0       1  The question in this election Who can put the ...
1       1  If we stand together theres nothing we cant do...
2       1  Both candidates were asked about how theyd con...
3       0  Join me for a 3pm rally tomorrow at the MidAme...
4       1  This election is too important to sit out Go t...

In [4]:
#drop any null colomuns
new_df2drop=new_df2.dropna()

In [5]:
#use below code to download and install NLTK package

#import nltk
#nltk.download()

In [27]:
#remove stopwords
from nltk.corpus import stopwords

def no_user_alpha(tweet):
        clean_mess = [word for word in tweet.split() if word.lower() not in stopwords.words('english')]
        return clean_mess
    
new_df2drop['cleantext']=new_df2drop['text'].apply(lambda x:no_user_alpha(x))

new_df2drop['cleantext']=new_df2drop['cleantext'].apply(lambda x:" ".join(x))

new_df2drop
   



C:\Users\Nabil\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
C:\Users\Nabil\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.


handle                                               text  \
0          1  The question in this election Who can put the ...   
1          1  If we stand together theres nothing we cant do...   
2          1  Both candidates were asked about how theyd con...   
3          0  Join me for a 3pm rally tomorrow at the MidAme...   
4          1  This election is too important to sit out Go t...   
...      ...                                                ...   
5643       0  lilredfrmkokomo realDonaldTrump My Facebook Gr...   
5644       0  marybnall01 realDonaldTrump watched lowell mas...   
5645       0  ghosthunter_lol Iowa key endorsement for realD...   
5646       0  iLoveiDevices EdwinRo47796972 happyjack225 Fox...   
5647       0  SalRiccobono realDonaldTrump troyconway Donald...   

                                              cleantext  
0     question election put plans action make life b...  
1     stand together theres nothing cant Make sure y...  
2     candidates asked theyd confront racial injusti...  
3     Join 3pm rally tomorrow MidAmerica Center Coun...  
4     election important sit Go make sure youre regi...  
...                                                 ...  
5643  lilredfrmkokomo realDonaldTrump Facebook Group...  
5644  marybnall01 realDonaldTrump watched lowell mas...  
5645  ghosthunter_lol Iowa key endorsement realDonal...  
5646  iLoveiDevices EdwinRo47796972 happyjack225 Fox...  
5647  SalRiccobono realDonaldTrump troyconway Donald...  

[5645 rows x 3 columns]

In [29]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [12]:

import sys
import argparse
import logging
from logging import critical, error, info, warning, debug

import numpy as np
import seaborn as sn
import pandas as pd
import random

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, TfidfTransformer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.feature_extraction import DictVectorizer
from nltk.stem.wordnet import WordNetLemmatizer
from sklearn.model_selection import train_test_split



In [13]:
X = new_df2drop['cleantext']
y = new_df2drop['handle']

y

0       1
1       1
2       1
3       0
4       1
       ..
5643    0
5644    0
5645    0
5646    0
5647    0
Name: handle, Length: 5645, dtype: int64

In [14]:
msg_train, msg_test, label_train, label_test = train_test_split(new_df2drop['cleantext'], new_df2drop['handle'], test_size=0.2)

In [15]:
pipeline = Pipeline([
    ('bow',CountVectorizer()),  # strings to token integer counts
    ('tfidf', TfidfTransformer()),  # integer counts to weighted TF-IDF scores
    ('classifier', MultinomialNB()),  # train on TF-IDF vectors w/ Naive Bayes classifier
])
pipeline.fit(msg_train,label_train)

Pipeline(memory=None,
         steps=[('bow',
                 CountVectorizer(analyzer='word', binary=False,
                                 decode_error='strict',
                                 dtype=<class 'numpy.int64'>, encoding='utf-8',
                                 input='content', lowercase=True, max_df=1.0,
                                 max_features=None, min_df=1,
                                 ngram_range=(1, 1), preprocessor=None,
                                 stop_words=None, strip_accents=None,
                                 token_pattern='(?u)\\b\\w\\w+\\b',
                                 tokenizer=None, vocabulary=None)),
                ('tfidf',
                 TfidfTransformer(norm='l2', smooth_idf=True,
                                  sublinear_tf=False, use_idf=True)),
                ('classifier',
                 MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))],
         verbose=False)

In [16]:

predictions = pipeline.predict(msg_test)

print(classification_report(predictions,label_test))
print ('\n')
print(confusion_matrix(predictions,label_test))
print(accuracy_score(predictions,label_test))

              precision    recall  f1-score   support

           0       0.95      0.92      0.93       618
           1       0.91      0.94      0.92       511

    accuracy                           0.93      1129
   macro avg       0.93      0.93      0.93      1129
weighted avg       0.93      0.93      0.93      1129



[[569  49]
 [ 33 478]]
0.9273693534100974


In [17]:
newtweet2="Libya"

newtweet = {'handle':  [0],
        'text': newtweet2}

newtweetdf= pd.DataFrame (newtweet, columns = ['handle','text'])

newtweetdf


handle   text
0       0  Libya

In [23]:
pipeline.predict(newtweetdf['text'].values)

array([0], dtype=int64)

In [26]:
newtweetdf['text'][0]

'Libya'

In [18]:

predictions = pipeline.predict(newtweetdf['text'])
#print(confusion_matrix(predictions,label_test))
probability = pipeline.predict_proba(newtweetdf['text'])
TrumpHillaryScore=predictions[0]

print(TrumpHillaryScore)

#print(accuracy_score(predictions,1))
print(probability)

0
[[0.68971843 0.31028157]]


In [19]:
from sklearn.externals import joblib
scaler_filename = "scaler.save"
joblib.dump(pipeline, scaler_filename) 

C:\Users\Nabil\Anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


['scaler.save']